name: Build & Deploy

on:
  push:
    branches:
      - pipeline-devops

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          echo "$PRIVATE_SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ${{secrets.NGINX_MASTER_USERNAME}}@${{secrets.NGINX_MASTER_IP}} 'bash -s' < ./demo.sh
        env:
          PRIVATE_SSH_KEY: ${{secrets.NGINX_MASTER_PVTKEY}}

         
