name: Build & Deploy

on:
  push:
    branches:
      - pipeline-devops

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$NGINX_MASTER_PVTKEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh-keyscan $NGINX_MASTER_IP >> ~/.ssh/known_hosts
          ssh -i ssh_key.pem $NGINX_MASTER_USERNAME@$NGINX_MASTER_IP 'bash -s' < ./demo.sh
        env:
          NGINX_MASTER_PVTKEY: ${{ secrets.NGINX_MASTER_PVTKEY }}
          NGINX_MASTER_IP: ${{ secrets.NGINX_MASTER_IP }}
          NGINX_MASTER_USERNAME: ${{ secrets.NGINX_MASTER_USERNAME }}
